steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-gpt2-large', '.']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'fastapi-gpt2-large',
         '--image', 'gcr.io/$PROJECT_ID/fastapi-gpt2-large',
         '--region', 'asia-south1',
         '--memory', '8Gi',
         '--cpu', '2',
         '--allow-unauthenticated',
         '--timeout', '1200',
         '--port', '8080',
         '--platform', 'managed']
